name: Test

on:
  workflow_dispatch:
    inputs:
      branch-name:
        type: string
        default: test-branch

jobs:
  print:
    runs-on: ubuntu-22.04
    permissions: read-all
    steps:
      - run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/branches/${{ github.event.repository.default_branch }}/protection
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        id: get_branch_protection
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/${{ github.repository }}/branches/${{ github.event.repository.default_branch }}/protection
          # script: |
            # const owner = context.payload.repository.owner.login;
            # const repo = context.payload.repository.name;
            # strict_required_status_checks_policy
      - run: "echo '${{ steps.get_branch_protection.outputs.data }}'"
  required_status_checks:
    name: Required Test Status Checks
    runs-on: ubuntu-latest
    needs:
      - print
    if: always()
    steps:
      - run: |
          [ '${{ needs.print.result }}' = 'success' ] || (echo print failed && false)
