name: Test LXD
on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo lxd init --auto
      - run: sudo lxc remote add craft-com.ubuntu.cloud-buildd https://cloud-images.ubuntu.com/buildd/releases --protocol=simplestreams
      - run: sudo lxc image list craft-com.ubuntu.cloud-buildd:
      - run: sudo lxc launch craft-com.ubuntu.cloud-buildd:5de93bcc5cddf2ede3e74f88c313deb056eab006dd131618a5d412dc4a5e5534 test
