name: Test create-pull-request
on:
  workflow_dispatch:

jobs:
  update-lib:
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    name: Check libraries
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Update
        run: echo foobar > foobar
      - name: Create pull request
        uses: canonical/create-pull-request@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "test create-pull-request"
          branch-name: "test/create-pull-request"
          title: Test create-pull-request
          body: Test create-pull-request
          upsert: true
          ignore-no-changes: true
          auto-merge: true
