name: Test LXD
on: 
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run: curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz -o /dev/null
      - run: curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz -o /dev/null
      - run: curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz -o /dev/null
      - run: curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz -o /dev/null
      - run: curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz -o /dev/null
      - run: curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz -o /dev/null
      - run: curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz -o /dev/null
      - run: curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz -o /dev/null
      - run: curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz -o /dev/null
      - run: curl https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.18.tar.gz -o /dev/null
