name: Test LXD
on: 
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo lxd init --auto
      - run: sudo lxc launch ubuntu:24.04 test
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
