name: Test LXD
on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh run download 5331876766 -R canonical/indico-operator
      - run: ls -lah indico
      - run: sudo snap install microk8s --classic
      - run: sudo microk8s status --wait-ready
      - run: |
          cat indico/indico.tar | sudo microk8s ctr image import -
      - run: |
          sudo /snap/microk8s/current/bin/ctr -a /var/snap/microk8s/common/run/containerd.sock -n k8s.io image ls
      - run: |
          cat << EOF > indico.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: indico-deployment
            labels:
              app: indico
          spec:
            selector:
              matchLabels:
                app: indico
            template:
              metadata:
                labels:
                  app: indico
              spec:
                containers:
                - name: indico
                  image: indico:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                  - containerPort: 80
          EOF
          sudo microk8s kubectl apply -f indico.yaml
      - run: |
          while :; do
            sudo microk8s kubectl get pods
            sleep 1
          done

